development:
  adapter: postgresql
  encoding: unicode
  database: flashcards_dev
  pool: 5
  # username: macbook
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: flashcards_test
  pool: 5
  # username: macbook
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>
