# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: flashcards_dev
  pool: 5
  username: Macbook
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: flashcards_test
  pool: 5
  username: Macbook
  password:
